### ISSUE TITLE
Re-design generate Page

### ISSUE THREAD

**Issue by redoC-A2k** [MFarabi619/hackateer#19]
I will roughly need , 
A problem statement input field,
Duration of hackathon ( in days )  so it will be of type number,
Members of the team and then accordingly you will show the fields below
Then details of the team like 
Name of the person 1 : then a multi select field to select the tech stack they are familiar or are comfortable with 
Name of the person 2 : multi select field for person 2
....
and so on for all the team members

**Comment by MFarabi619** [comment]
![Generate Page V2](https://github.com/MFarabi619/hackateer/assets/54924158/37a5370a-5f2b-4865-87c9-9728a8ba9f16)

How is this for the design?
