### ISSUE TITLE
Bootstrap and deploy Next.js project

### ISSUE THREAD

**Issue by MFarabi619** [MFarabi619/hackateer#8]
Get started with a basic boilerplate, and create a well-defined structure to ensure the project scales well.

**Comment by MFarabi619** [comment]
@redoC-A2k Still working on the design. The Navbar will should have a logo, an animated hamburger icon, and the following navbar links:

- Home
- About (A page where we will write the story of how this project came to be)
- Resources (A page with helpful materials such as hackathon guides, success stories, pitfalls, etc.)
- Contact (This page will have the information of the Hackateer team)
- Sign in/Sign up
- Profile (When logged in)

Reply or react to this comment once you've seen it :)

**Comment by redoC-A2k** [comment]
Take your time and make a fabulous and clean ui , appropiate to the project as you see fit ! (Even if the ui gets difficult to implement for me don't worry about me , If I feel I will get to you for help)
And I also need some time to get familiar with tailwind .

**Comment by MFarabi619** [comment]
@redoC-A2k You can get started on the basic html and css for the navbar component. The color palette is on figma is complete, so feel free to add the colors to your tailwind config. This way you won't have to use hex codes, and can just reference the colors by variable name. [Figma Design Link](https://www.figma.com/file/eKv7G9w8Oaxf3wqYZ664X5/Hackateer?type=design&node-id=0%3A1&mode=design&t=qnzd0KwouOZ0lMHp-1)
